userapp/urls.py
from userapp import views
from django.urls import path
from django.contrib.auth.views import LogoutView
app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLoginView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('createtoken/', views.create_token, name='create_token'),
]

whatis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from xxapp.api_views import VacancyViewSet, ArticleViewSet, SkillViewSet

router = routers.DefaultRouter()
router.register(r'vacancyes', VacancyViewSet)
router.register(r'articles', ArticleViewSet)
router.register(r'skills', SkillViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('xxapp.urls', namespace='xxapp')),
    path('users/', include('userapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/vacancyes/', include(router.urls)),
    path('api/v0/articles/', include(router.urls)),
    path('api/v0/', include(router.urls)),
]
if settings.DEBUG:
    import  debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


# if settings.DEBUG:
#  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xxapp/urls.py
from xxapp import views
from django.urls import path

app_name = 'xxapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('address/', views.contact, name='contact'),
    path('zapros/', views.zapros, name='zapros'),
    path('base/', views.zaprosb, name='zaprosb'),
    path('loadart/', views.loadart, name='loadart'),
    path('vacancy/', views.VacancyView.as_view(), name='vacancyl'),
    path('vacancyc/', views.VacancyCreate.as_view(), name='vacancyc'),
    path('vac_update/<int:pk>/', views.VacancyUpd.as_view(), name='vac_update'),
    path('vac_delete/<int:pk>/', views.VacDeleteView.as_view(), name='vac_delete'),
    path('vac_det/<int:pk>/', views.VacDetailView.as_view(), name='vac_det'),
    path('article/', views.ArticleView.as_view(),  name='article'),
    path('articled/<int:pk>/', views.ArtDeleteView.as_view(),  name='art_del'),
    path('vacancyp/', views.postr_vyvod, name='vacancyp'),

]

xxapp/models.py
from django.db import models
from userapp.models import XxUser


# Create your models here. для хранения моделей

class ActiveManager(models.Manager):

    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)


class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    #is_active = models.BooleanField(default=False)

    class Meta:
        abstract = True


class TimeStamp(models.Model):
    """
    Abstract - для нее не создаются новые таблицы
    данные хранятся в каждом наследнике
    """
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Vacancy(TimeStamp, models.Model):

    vac = models.CharField(max_length=30, verbose_name='Вакансия', null = True, blank=True)
    reg = models.CharField( max_length=30, verbose_name='Регион', null = True, blank=True)
    num = models.IntegerField(verbose_name='Количество', null = True, blank=True)
    user = models.ForeignKey(XxUser, on_delete = models.CASCADE, null = True, blank=True)
    #null = True, blank=True - записать пустыми данными создаваемые поля

    def some_met(self):
        return 'Who Are You?'

    def __str__(self):
         return f'{self.vac} {self.reg}  {self.num}'

    # @classmethod
    # def create_user(cls, username, email, password):
    #     pass



class Skill(TimeStamp, models.Model):

    skl = models.CharField(max_length=300, verbose_name='Требуемые знания', null = True, blank=True)
    reg = models.CharField(max_length=30, verbose_name='Регион', null = True, blank=True)
    user = models.ForeignKey(XxUser, on_delete = models.CASCADE, null = True, blank=True)
    def __str__(self):
        return f'{self.skl} {self.reg}'


class Article(TimeStamp,  IsActiveMixin):

    art = models.TextField(blank=True,null = True)
    ul = models.URLField(max_length=256,null = True, blank=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.art} {self.ul}'

xxapp/forms.py
from django import forms
from .models import Article, Vacancy, Skill

class Vacform(forms.Form):

    vac = forms.CharField(label='Наименование вакансии:')
    reg = forms.CharField(label='В каком регионе ищем :')
    class Meta:
        model = Vacancy
        # fields = '__all__'
        exclude =  ('user',)

class Vacforml(forms.ModelForm):
    vac = forms.CharField(label = 'Название вакансии')
    reg = forms.CharField(label = 'Название региона')
    num = forms.IntegerField(label = 'Количество вакансий')
    class Meta:
        model = Vacancy
        # fields = '__all__'
        exclude =  ('user',)

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        #fields = '__all__'
        exclude =  ('user',)

class ArticleForm(forms.ModelForm):
    art = forms.CharField(label = 'Название статью:')
    ul = forms.URLField(label = 'Ссылка на статью:')
    class Meta:
        model = Article
        #fields = '__all__'
        exclude =  ('user',)

xxapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .forms import Vacform,Vacforml, ArticleForm
from xxapp.models import Vacancy, Skill, Article
import requests
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from bs4 import BeautifulSoup


@user_passes_test(lambda u: u.is_superuser)
def loadart(request):
    if request.method == "GET":
        url = 'https://3dnews.ru/news'
        r = requests.get(url)
        r.encoding = 'win1251'
        html = r.text
        soup = BeautifulSoup(html, 'lxml')
        head = soup.find('div', id='section-content').find_all('a', class_="entry-header")
        for i in head:
            link = 'https://3dnews.ru' + i.get('href')
            heads= i.find('h1').string
            data = {'head': heads,'link': link}
            Article.objects.create(art=data['head'], ul=data['link'])
        return HttpResponseRedirect(reverse('xxapp:article'))
    else:
        return HttpResponseRedirect(reverse('xxapp:article'))


# Create your views here. логика сайта
def main_view(request):
    return render(request, 'xxapp/indext.html', context={})

def contact(request):
    return render(request, 'xxapp/address.html', context={})
@login_required
def zapros(request):
    if request.method == "POST":
         form = Vacform(request.POST)
         if form.is_valid():
            vac = form.cleaned_data['vac']
            reg = form.cleaned_data['reg']
            rg = {"Москва":1, "Санкт-Петербург":2, "Россия":113,"ДРУГИЕ РЕГИОНЫ":1001,"УКРАИНА":5,"БЕЛОРУССИЯ":16,"Казахстан":40,"ЕЙСК":70}
            region = rg[reg]
            domain = 'https://api.hh.ru/'
            url = f'{domain}vacancies'
            params = {}
            params['text'] = vac
            params['area'] = region
            result = requests.get(url, params=params).json()
            all_found_vac = result['found']
            vse_stranitsy = result['found'] // 100 + 1 if result['found'] // 100 <= 20 else 20
            vse_skily = {}
            for i in range(vse_stranitsy):
                    params['page'] = i
                    result = requests.get(url, params=params).json()
                    for j in result['items']:
                        rez_tmp = requests.get(j['url']).json()
                        for i in rez_tmp['key_skills']:
                            if i['name'] in vse_skily:
                                vse_skily[i['name']] += 1

                            else:
                                vse_skily.setdefault(i['name'], 1)

                        if all_found_vac == False: all_found_vac = 0
                        print(vac, reg, region, all_found_vac, vse_skily)
                        skl = list({name: dict.keys for name in dict.keys(vse_skily)})
                        #skl = str(skl)
                        Vacancy.objects.create(vac=vac, reg=reg, num = all_found_vac)
                        Skill.objects.create(skl=skl, reg=reg)
                        return render(request, 'xxapp/rezultat.html', context={'vacanc': vac, 'area': reg, 'salary': all_found_vac, 'data':vse_skily})
         else:
            form = Vacform()
            return render(request, 'xxapp/zaprost.html', context={'form': form})
    else:
        form = Vacform()
        return render(request, 'xxapp/zaprost.html', context={'form': form})

def rezultatb(request):
    return render(request, 'xxapp/rezultatb.html', context={})

def zaprosb(request):
   
    if request.method == "GET":
        forml = Vacforml()
        return render(request, 'xxapp/zaprosb.html', context={'form': forml})
    else:
        forml = Vacforml(request.POST)
        if forml.is_valid():
            #Добавить в форму текущего пользователя - request.user
            forml.instance.user = request.user
            forml.save()
            return render(request, 'xxapp/vacancyl1.html', context={'forml': forml})
        else:
         return render(request, 'xxapp/zaprosb.html', context={'form': forml})

def postr_vyvod(request):
    vacanc = Vacancy.objects.all()
    paginator = Paginator(vacanc, 4)

    page = request.GET.get('page')
    try:
        vacanc = paginator.page(page)
    except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            vacanc = paginator.page(1)
    except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            vacanc = paginator.page(paginator.num_pages)
            #title ='СПИСОК ВАКАНСИЙ'
            #title = title.capitalize()
    return render(request, 'vacancylp.html', context={'vacs': vacanc, 'vacanc':vacanc})

class NameContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)

        context['vac'] = 'РЕДАКТИРОВАНИЕ'
        context['reg'] = 'РЕГИОН'
        context['det'] = 'ДЕТАЛИ ПО ДАННОЙ ВАКАНСИИ:'
        context['title'] = ''
        return context


class VacancyView(ListView):
    model = Vacancy
    fields = '__all__'
    template_name = 'vacancyl.html'
    context_object_name = 'vacs'
    paginate_by = 6

    def get_queryset(self):
            """
            Получение данных
            :return:
            """
            return Vacancy.objects.all().select_related()

class VacancyCreate(LoginRequiredMixin, CreateView, NameContextMixin):
    fields = ('vac','reg', 'num')
    model = Vacancy
    success_url = reverse_lazy('xxapp:vacancyl')
    template_name = 'vacancycreate.html'



    def form_valid(self, form):
        #self.request.user - текущий пользователь
        form.instance.user = self.request.user
        return super().form_valid(form)

class VacancyUpd(LoginRequiredMixin,UpdateView,NameContextMixin):
    fields = ('vac','reg', 'num')
    model = Vacancy
    context_object_name = 'vacs'
    success_url = reverse_lazy('xxapp:vacancyl')
    template_name = 'vacancycreate.html'
    def form_valid(self, form):
        #self.request.user - текущий пользователь
        form.instance.user = self.request.user
        return super().form_valid(form)

class VacDeleteView(LoginRequiredMixin,DeleteView,NameContextMixin):
    fields = '__all__'
    model = Vacancy
    context_object_name = 'vacs'
    success_url = reverse_lazy('xxapp:vacancyl')
    template_name = 'del_confirm.html'
    

class ArticleView(ListView,NameContextMixin):
    model = Article
    template_name = 'article.html'
    paginate_by = 10
    def get_queryset(self):
            """
            Получение данных
            :return:
            """
            return Article.active_objects.all().select_related()


class ArtDeleteView(LoginRequiredMixin,DeleteView,NameContextMixin):

    model = Article
    template_name = 'del_confirm.html'
    success_url = reverse_lazy('xxapp:article')


class VacDetailView(DetailView, NameContextMixin):
    model = Skill
    template_name = 'vac_detail.html'
    success_url = reverse_lazy('xxapp:vacancyl')
    context_object_name = 'skl'
    def get(self, request, *args, **kwargs):
        self.skill_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        
        return get_object_or_404(Skill, pk=self.skill_id)

# class Load():
#     model = Article
#     template_name = 'article.html'
#     success_url = reverse_lazy('xapp:article')
#         

xxapp/templates/article.html
{% extends "base1.html" %}
{% block title %} {{artlist}} {% endblock %}


{% block content %}

<div>
      На данной странице {{object_list|length}} ст.
   <h1> Статьи 3DNEWS и ссылки на них НАШЕЙ БАЗЕ: </h1><br>

       <a href="{% url 'xxapp:loadart' %}">
       <font color="green"> ЕЩЕ ЗАГРУЗИТЬ СТАТЬИ ? </font>
        
        {%for item in object_list%}

        <li>
            Статья: {{item.art}}
            <a class="nav-link" href="{{item.ul}}"> {{item.ul}} </a> 
        </li>

		<a href="{% url 'xxapp:art_del' pk=item.pk %}">
        <font color="red"> Удалить статью? </font>
        </a>

        {% endfor %}
       <a href="{% url 'xxapp:loadart' %}">
       <font color="green"> ЕЩЕ ЗАГРУЗИТЬ СТАТЬИ ? </font>
       </a>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая </a>
            <a href="?page={{ page_obj.previous_page_number }}">ПРЕДЫДУЩАЯ</a>
        {% endif %}

        <span class="current">
             {{ page_obj.number }}-я страница из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">СЛЕДУЮЩАЯ</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
    </div>
</div>
            


{% endblock %}

xxapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
 <meta charset="UTF-8">
    <head>
        <title>{% block title %}{% endblock %}</title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link href= "/static/css/style.css" rel="stylesheet" type="text/css"/>
    </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/zapros/"> ФОРМА ПОИСКА по ХХ на сайте HH.RU </a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="/base/"> ВВЕСТИ ВАКАНСИИ В "местную" БАЗУ </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/vacancy/"> ВАКАНСИИ В "местной" БАЗЕ </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/article/"> Статьи </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/address/"> КОНТАКТЫ </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        Здрасьте :), <a href="{% url 'users:profile' pk=user.pk %}">{{user.username}} !</a>
                        <a class="nav-link" href="{% url 'users:logout' %}" > Выход </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}" > Вход </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}" > Регистрация </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <hr><br><br>
    <div class="container">
        
        {% block content %}{% endblock %}

    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

xxapp/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html>
 <meta charset="UTF-8">
    <head>
        <title>{% block title %}{% endblock %}</title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/zapros/"> ФОРМА ПОИСКА по ХХ </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/base/"> ВВЕСТИ ВАКАНСИИ В БАЗУ </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/vacancy/"> ВАКАНСИИ В ЛОКАЛЬНОЙ БАЗЕ </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/article/"> Статьи </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/address/"> КОНТАКТЫ </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                 Здрасьте :), <a href="{% url 'users:profile' pk=user.pk %}">{{user.username}} !</a>
                <a class="nav-link" href="{% url 'users:logout' %}" > Выход </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}" > Вход </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}" > Регистрация </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<hr><br><br>
<div class="container">

    {% block content %}{% endblock %}

</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

xxapp/templates/del_confirm.html
{% extends "base1.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div>
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>
    <li> ВЫ ТОЧНО УВЕРЕНЫ, ЧТО ХОТИТЕ УДАЛИТЬ ИМЕННО ЭТУ ЗАПИСЬ? 
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger"> Конечно же :)</button>
    </form>
    </li>
</div>
{% endblock %}

xxapp/templates/vac_detail.html
{% extends "base1.html" %}
{% block title %} ПОДРОБНОСТИ {% endblock %}


{% block content %}


     
    <h1>{{det}}</h1><br>
    
<div class="row">
    
    <div class="col-lg-8 col-md-10 mx-auto">
        {{skl}}
    </div>
    <a href="{% url 'xxapp:vac_update' pk=skl.pk %}">
            Изменить
        </a>
</div>




{% endblock %}

xxapp/templates/vacancycreate.html
{% extends "base1.html" %}
{% block title %} ВВОД ВАКАНСИЙ {% endblock %}


{% block content %}
{% csrf_token %}
<div>
           
    <h1> ВВЕДИТЕ/ИЗМЕНИТЕ ДАННЫЕ ПО ВАКАНCИИ ДЛЯ СОХРАНЕНИЯ В НАШЕЙ БАЗЕ: </h1><br>
        
    <div class="row">
    <h1>{{vac}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{item.pk}}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary"> Сохранить </button>
        </form>
    </div>
</div>
</div>
            


{% endblock %}

xxapp/templates/vacancyl.html
{% extends "base1.html" %}
{% block title %} СПИСОК ВАКАНСИЙ {% endblock %}


{% block content %}
{% csrf_token %}
<div>
        
    <h1> ВОТ, ЧТО НАШЛОСЬ В НАШЕЙ БАЗЕ: </h1><br>

    /
        <a  href="{% url 'xxapp:vacancyc' %}" > ДЛЯ СОЗДАНИЯ ВАКАНСИИ НАЖМИТЕ НА "ЭТОТ ТЕКСТ", чтобы отредактировать вакансию нажмите на САМУ вакансию:  </a>
    \    

        {%for item in vacs %}
            <li>
            <a href="{% url 'xxapp:vac_update' pk=item.pk %}">
            В регионе {{item.reg}} по запросу {{item.vac}} есть {{item.num}} вакансий 
            </a>

            /
            <a href="{% url 'xxapp:vac_det' pk=item.pk %}">
            <font color="green">Посмотреть детали?</font>
            </a>

            /
            <a href="{% url 'xxapp:vac_delete' pk=item.pk %}">
            <font color="red">Удалить вакансию?</font>
            </a>

            </li>
    
        {% endfor %}
      На данной странице {{vacs|length}} ваканcий

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая </a>
            <a href="?page={{ page_obj.previous_page_number }}">ПРЕДЫДУЩАЯ</a>
        {% endif %}

        <span class="current">
             {{ page_obj.number }}-я страница из {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">СЛЕДУЮЩАЯ</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
    </div>
   </div>
   </div> 
</div>
            


{% endblock %}

xxapp/templates/vacancylp.html
{% extends "base1.html" %}
{% block title %} СПИСОК ВАКАНСИЙ {% endblock %}


{% block content %}
{% csrf_token %}
<div>
     
    <h1> ВОТ, ЧТО НАШЛОСЬ В НАШЕЙ БАЗЕ: </h1><br>
     
    /
        <a  href="{% url 'xxapp:vacancyc' %}" > ДЛЯ СОЗДАНИЯ ВАКАНСИИ НАЖМИТЕ НА "ЭТОТ ТЕКСТ", чтобы отредактировать вакансию нажмите на САМУ вакансию:  </a>
    \    

        {%for item in vacs %}
            <li>
            <a href="{% url 'xxapp:vac_update' pk=item.pk %}">
            В регионе {{item.reg}} по запросу {{item.vac}} есть {{item.num}} вакансий 
            </a>

            /
            <a href="{% url 'xxapp:vac_det' pk=item.pk %}">
            <font color="green">Посмотреть детали?</font>
            </a>

            /
            <a href="{% url 'xxapp:vac_delete' pk=item.pk %}">
            <font color="red">Удалить вакансию?</font>
            </a>

            </li>
    
        {% endfor %}
        <!-- Pager -->

        <div class="clearfix">
            <div class="pagination">

            <span class="step-links">
                {% if vacanc.has_previous %}
                    <a href="?page={{ vacanc.previous_page_number }}">предыдущая страница</a>
                {% endif %}

                <span class="current">
                     {{ vacanc.number }}-я страница из {{ vacanc.paginator.num_pages }}
                </span>

                {% if vacanc.has_next %}
                <a href="?page={{ vacanc.next_page_number }}">следующая страница</a> 



                {% endif %}


            </span>
            </div>
        </div>
   </div> 
</div>
            


{% endblock %}